const elements = [
  { itemPic: "img/ic-abil-gold@2x.png", count: "153BD3", itemClass: "check" },
  { itemPic: "img/sh-icon-chest-128.png", count: "4", itemClass: "check" },
  { itemPic: "img/photo-ic@2x.png", count: "2", itemClass: "check" },
  { itemPic: "img/ms-stone-orange.png", count: "160", itemClass: "get" },
  { itemPic: "img/ms-stone-blue.png", count: "4", itemClass: "block" },
  { itemPic: "img/ms-stone-green.png", count: "4", itemClass: "block" },
  { itemPic: "img/ms-stone-pink.png", count: "4", itemClass: "block" },
  {
    itemPic: "img/evPopArts/potion_red@2x.png",
    count: "230",
    itemClass: "block",
  },
  { itemPic: "img/ic-abil-gold@2x.png", count: "153BD3", itemClass: "block" },
  { itemPic: "img/sh-icon-chest-128.png", count: "4", itemClass: "block" },
  { itemPic: "img/photo-ic@2x.png", count: "2", itemClass: "block" },
  { itemPic: "img/ms-stone-orange.png", count: "160", itemClass: "block" },
  { itemPic: "img/ms-stone-blue.png", count: "4", itemClass: "block" },
  { itemPic: "img/ms-stone-green.png", count: "4", itemClass: "block" },
  { itemPic: "img/ms-stone-pink.png", count: "4", itemClass: "block" },
  {
    itemPic: "img/evPopArts/potion_red@2x.png",
    count: "230",
    itemClass: "block",
  },
  { itemPic: "img/ic-abil-gold@2x.png", count: "153BD3", itemClass: "block" },
  { itemPic: "img/sh-icon-chest-128.png", count: "6", itemClass: "block" },
  { itemPic: "img/photo-ic@2x.png", count: "2", itemClass: "block" },
  { itemPic: "img/ms-stone-orange.png", count: "400", itemClass: "block" },
  { itemPic: "img/ms-stone-blue.png", count: "10", itemClass: "block" },
  { itemPic: "img/ms-stone-green.png", count: "10", itemClass: "block" },
  { itemPic: "img/ms-stone-pink.png", count: "10", itemClass: "block" },
  {
    itemPic: "img/evPopArts/potion_red@2x.png",
    count: "575",
    itemClass: "block",
  },
  { itemPic: "img/ic-ny-sneg-8.png", count: "5K", itemClass: "block" },
  { itemPic: "img/sh-icon-chest-128.png", count: "6", itemClass: "block" },
  { itemPic: "img/photo-ic@2x.png", count: "2", itemClass: "block" },
  { itemPic: "img/ms-stone-orange.png", count: "400", itemClass: "block" },
  { itemPic: "img/ms-stone-blue.png", count: "10", itemClass: "block" },
  { itemPic: "img/ms-stone-green.png", count: "10", itemClass: "block" },
  { itemPic: "img/ms-stone-pink.png", count: "10", itemClass: "block" },
  {
    itemPic: "img/evPopArts/potion_red@2x.png",
    count: "575",
    itemClass: "block",
  },
  { itemPic: "img/ic-ny-sneg-9.png", count: "5K", itemClass: "block" },
  { itemPic: "img/sh-icon-chest-128.png", count: "6", itemClass: "block" },
  { itemPic: "img/photo-ic@2x.png", count: "2", itemClass: "block" },
  { itemPic: "img/ms-stone-orange.png", count: "400", itemClass: "block" },
  { itemPic: "img/ms-stone-blue.png", count: "10", itemClass: "block" },
  { itemPic: "img/ms-stone-green.png", count: "10", itemClass: "block" },
  { itemPic: "img/ms-stone-pink.png", count: "10", itemClass: "block" },
  {
    itemPic: "img/evPopArts/potion_red@2x.png",
    count: "575",
    itemClass: "block",
  },
  { itemPic: "img/ic-abil-gold@2x.png", count: "153BD3", itemClass: "block" },
  { itemPic: "img/sh-icon-chest-128.png", count: "6", itemClass: "block" },
  { itemPic: "img/photo-ic@2x.png", count: "2", itemClass: "block" },
  { itemPic: "img/ms-stone-orange.png", count: "400", itemClass: "block" },
  { itemPic: "img/ms-stone-blue.png", count: "10", itemClass: "block" },
  { itemPic: "img/ms-stone-green.png", count: "10", itemClass: "block" },
  { itemPic: "img/ms-stone-pink.png", count: "10", itemClass: "block" },
  {
    itemPic: "img/evPopArts/potion_red@2x.png",
    count: "575",
    itemClass: "block",
  },
  { itemPic: "img/ic-ny-sneg-10.png", count: "5K", itemClass: "block" },
  { itemPic: "img/ic-ny-sneg-11.png", count: "5K", itemClass: "block" },
];

export default elements;
